### ISSUE TITLE
[Feature Request] Bollinger Bands Indicator

### ISSUE THREAD

**Issue by qmn1711** [sdcoffey/techan#20]
Do you have any plan for support Bollinger Bands indicator?

**Comment by sdcoffey** [comment]
Hey @qmn1711! My bad for taking so long to respond to this. I think that's a great idea. I don't have any specific plans, but I'd welcome a PR!

**Comment by sdcoffey** [comment]
@qmn1711 Bollinger bands are now available in v0.11.0!
