### ISSUE TITLE
should EMA consider time window?

### ISSUE THREAD

**Issue by SunRunAwayAwayAway** [sdcoffey/techan#42]
Hi, I see the implementation of EMA does not consider the time window, is it correct?
https://github.com/sdcoffey/techan/blob/572c478f546ecfef27a8454bd653f95829269490/indicator_exponential_moving_average.go#L24-L37

Also, is RSI correct since RSI relays on EMA?

**Comment by d01phin** [comment]
I think it's incorrect, window is not used anywhere in the calculation.

**Comment by sdcoffey** [comment]
Fixed as of 0.12.1! Shoutout to @danhenke and @joelnordell for the fix
