### ISSUE TITLE
Checkout-Java-SDK

### ISSUE THREAD

**Issue by MarErm27** [sdcoffey/techan#54]
Hello, Steve Coffey!
What is the difference between PayPal Orders API and Payments API from Checkout-Java-SDK?
Which one to use if I want to use authentications?
It is seems that Orders API not allows doing void of authorization. It feels like Order API is for use cases where you want to capture instantly and Payments API is for use cases when you want to use authorization, but it's not clear for me yet, am I right?

Orders API
https://developer.paypal.com/docs/api/orders/v2/

Payments API
https://developer.paypal.com/docs/api/payments/v2/

**Comment by sdcoffey** [comment]
Hey @MarErm27, closing this as not relevant to this package
