### ISSUE TITLE
What is the status of this package?

### ISSUE THREAD

**Issue by eduardhasanaj** [sdcoffey/techan#55]
Is this package maintained?
There some open pull requests that date to 2021.

**Comment by RabchikEngineer** [comment]
Would like to ask the same...

**Comment by sdcoffey** [comment]
Hi there! Thanks for asking. I'm doing my best to maintain this package while also working on my own startup. I will try to allocate some time over the next few weeks to clean up old PRs and fix some outstanding bugs.
