### ISSUE TITLE
does profit analyze support future?

### ISSUE THREAD

**Issue by beaquant** [sdcoffey/techan#7]
I found some profile analyze use exitvalue sub costbaseis, but in future, you could sell short first and then buy long.
does the profit analyze with order side?

**Comment by sdcoffey** [comment]
Hey @beaquant,

Sorry for letting this sit for a week! I see you put in a PR for this. Let me take a look and get back with you. I'm going to close this issue and we'll discuss in #6

**Comment by beaquant** [comment]
thanks
