### ISSUE TITLE
TotalProfitAnalysis with SHORT positions

### ISSUE THREAD

**Issue by awsom82** [sdcoffey/techan#9]
I've been looking into [code of TotalProfitAnalysis Analyze](https://github.com/sdcoffey/techan/blob/69f92bf61a62da7faa95001a02b6ddf160f9fc9a/analysis.go#L21).

It looks we have miscalculation for all short positions.

**Comment by sdcoffey** [comment]
Closing - thanks again for your PR @awsom82
